# speedcore aria2 配置 — 极限多线程下载
log-level=error
console-log-level=error
enable-rpc=true
rpc-listen-port=16800
rpc-listen-all=false
rpc-allow-origin-all=true
max-connection-per-server=16
split=128
min-split-size=1M
max-concurrent-downloads=32
max-overall-download-limit=0
max-download-limit=0
continue=true
file-allocation=falloc
disk-cache=128M
quiet=true
check-certificate=false
